name: Setup env
description: Sets up env for other jobs

inputs:
  environment:
    description: Envionment for bundle
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0

    - uses: actions/setup-node@v1
      with:
        node-version: 10.17.0
